# Generated by Django 5.1.7 on 2025-04-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parts', models.IntegerField(default=1)),
                ('color', models.CharField(max_length=100)),
            ],
        ),
    ]
