# Generated by Django 5.1.7 on 2025-06-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phoneUser',
            field=models.CharField(max_length=20),
        ),
    ]
