# Generated by Django 5.1.7 on 2025-05-29 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('muebles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateSale', models.DateField(auto_now=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('stateSale', models.BooleanField(default=True)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100)),
                ('productPrice', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalle_venta', to='muebles.muebles')),
                ('ventaID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalle_venta', to='ventas.ventas')),
            ],
        ),
    ]
