# Generated by Django 5.1.7 on 2025-04-28 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('muebles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateSale', models.DateField()),
                ('amountSale', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('stateSale', models.BooleanField(default=True)),
                ('furnitureID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='muebles.muebles')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
