# Generated by Django 5.1.7 on 2025-05-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='ratings',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
