# Generated by Django 5.2.2 on 2025-06-08 01:35

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0002_alter_categorias_namecategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Muebles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameFurniture', models.CharField(max_length=100)),
                ('descriptionFurniture', models.CharField(max_length=225)),
                ('priceFurniture', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('stateFurniture', models.BooleanField(default=True)),
                ('imageFurniture', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias', to='categorias.categorias')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
