# Generated by Django 5.1.7 on 2025-04-01 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        ('contenido', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muebles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameFurniture', models.CharField(max_length=100)),
                ('descriptionFurniture', models.CharField(max_length=225)),
                ('priceFurniture', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('stateFurniture', models.BooleanField(default=True)),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias', to='categorias.categorias')),
                ('contenidoID', models.ManyToManyField(to='contenido.contenido')),
            ],
        ),
    ]
