# Generated by Django 5.1.7 on 2025-06-20 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameFurniture', models.CharField(max_length=100)),
                ('descriptionFurniture', models.CharField(max_length=1500)),
                ('priceFurniture', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('porcentajeDescuento', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('stateFurniture', models.BooleanField(default=True)),
                ('imageFurniture', models.TextField(blank=True, null=True)),
                ('categoryID', models.ManyToManyField(related_name='productos', to='categorias.categorias')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
