# Generated by Django 5.1.7 on 2025-06-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imageFurniture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
