# Generated by Django 5.1.7 on 2025-06-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0003_alter_categorias_namecategory'),
        ('productos', '0002_alter_productos_imagefurniture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='categoryID',
        ),
        migrations.AddField(
            model_name='productos',
            name='categoryID',
            field=models.ManyToManyField(related_name='productos', to='categorias.categorias'),
        ),
    ]
