# Generated by Django 5.1.7 on 2025-06-13 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_remove_productos_categoryid_productos_categoryid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='descriptionFurniture',
            field=models.CharField(max_length=725),
        ),
    ]
