# Generated by Django 5.1.7 on 2025-06-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_productos_descriptionfurniture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='descriptionFurniture',
            field=models.CharField(max_length=1500),
        ),
    ]
