# Generated by Django 5.1.7 on 2025-04-07 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('muebles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('FurnitureID', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='muebles.muebles')),
            ],
        ),
    ]
