# Generated by Django 5.1.7 on 2025-06-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footerdata',
            name='email',
        ),
        migrations.AddField(
            model_name='footerdata',
            name='emails',
            field=models.JSONField(default=list),
        ),
    ]
