# Generated by Django 5.1.7 on 2025-06-14 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encargos', '0001_initial'),
        ('productos', '0005_alter_productos_descriptionfurniture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoproducto',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='pedidoproducto',
            name='producto',
        ),
        migrations.CreateModel(
            name='Encargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encargos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoEncargado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('encargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_encargados', to='encargos.encargo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.productos')),
            ],
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='PedidoProducto',
        ),
    ]
