# Generated by Django 5.1.7 on 2025-06-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encargos', '0002_remove_pedidoproducto_pedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encargo',
            name='estado',
            field=models.CharField(choices=[('carrito', 'Carrito'), ('procesado', 'Procesado'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='carrito', max_length=20),
        ),
    ]
