# Generated by Django 5.1.7 on 2025-06-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encargos', '0003_encargo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encargo',
            name='estado',
            field=models.CharField(choices=[('carrito', 'Carrito'), ('procesado', 'Procesado'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado'), ('papelera', 'Papelera'), ('pendiente', 'Pendiente')], default='carrito', max_length=20),
        ),
    ]
