# Generated by Django 5.2.2 on 2025-06-08 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_alter_categorias_namecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='nameCategory',
            field=models.CharField(max_length=100),
        ),
    ]
